[package]
name = "openglider-rs"
version = "0.1.3"
edition = "2021"

[lib]
name = "rs"
path = "openglider_rs/lib.rs"
crate-type = ["cdylib"]

[features]
default = []
inspect = ["pyo3/experimental-inspect"]

[[bin]]
name = "pyo3_stub_gen"
path = "openglider_rs/stub_gen.rs"

[dependencies]
anyhow = "1"
pyo3 = { version = "0.29" }
nalgebra = { version = "0.34", default-features = false, features = ["std"] }
pyo3-introspection = "0.29"
spade = "2"
wgpu = "0.20"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }
raw-window-handle = "0.6"
resvg = "0.48.1"
tiny-skia = "0.12"
usvg = "0.48.1"
png = "0.17"
serde_json = "1"

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl = "2.21"

[profile.release]
opt-level = 3
lto = "fat"        # or "thin" for faster compile times
codegen-units = 1  # enables better cross-module optimization
panic = "abort"    # if you don't need unwinding
strip = true       # smaller binary
