[metadata]
name = openglider
version = attr: openglider.version.__version__
author = airG products
author_email = simon@airg.family
description = A python library for paraglider design
long_description = file: README.md, LICENSE.md
keywords = paraglider, flying
license = GPL-v3
classifiers =
    Programming Language :: Python :: 3

[options]
zip_safe = True
include_package_data = False
packages = find:
python_requires = >=3.11
install_requires =
    pandas
    pydantic
    svgwrite
    numpy
    scipy
    ezdxf
    odfdo
    lxml
    packaging
    reportlab
    svglib

[options.package_data]
openglider = py.typed, *.pyi, rs/*.pyi, **/*.csv, **/*.svg, **/*.png, **/*.qss, **/*.ods, **/*.dat, **/*.json

[options.entry_points]
console_scripts =
    executable-name = openglider.gui:start_main_window

[options.extras_require]
gui = 
    qtpy
    pyside6
    qtawesome
    qasync
    qtmodern
    qtconsole
    debugpy
    pyqtgraph
    matplotlib
    vtk

[options.packages.find]
exclude =
    *.tests
    *.tests.*