from openglider.airfoil.generators.joukowsy import JoukowskyAirfoil
from openglider.airfoil.generators.treffz import TrefftzKuttaAirfoil
from openglider.airfoil.generators.vandevooren import VanDeVoorenAirfoil
from openglider.airfoil.generators.naca import compute_naca