from .vector import Vector3D
from collections.abc import Sequence
def find_duplicates(points: Sequence[Vector3D], max_distance: float) -> list[tuple[int, int]]: ...
def triangle_area(a: float, b: float, c: float) -> float: ...
def version() -> str: ...
