from .vector import PolyLine2D, Vector2D, Vector3D
from collections.abc import Sequence
from typing import Any, final

@final
class Line:
    def __new__(cls, /, a: int, b: int) -> Line: ...
    @property
    def a(self, /) -> int: ...
    @a.setter
    def a(self, /, value: int) -> None: ...
    def as_tuple(self, /) -> tuple[int, int]: ...
    @property
    def b(self, /) -> int: ...
    @b.setter
    def b(self, /, value: int) -> None: ...

@final
class Mesh:
    def __add__(self, /, other: object) -> Mesh: ...
    def __copy__(self, /) -> Mesh: ...
    def __deepcopy__(self, /, _memo: Any) -> Mesh: ...
    def __getitem__(self, /, item: str) -> Mesh: ...
    def __json__(self, /) -> tuple[list[Vector3D], dict[str, list[tuple[Any, Any]]], dict[str, list[int]]]: ...
    def __new__(cls, /, name: str = ...) -> Mesh: ...
    def __repr__(self, /) -> str: ...
    def add_line(self, /, object_index: int, line: Line) -> None: ...
    def add_object(self, /, name: str, color: tuple[int, int, int] = ..., textured: bool = False) -> int: ...
    def add_point(self, /, point: Vector3D) -> int: ...
    def add_quad(self, /, object_index: int, quad: Quad) -> None: ...
    def add_triangle(self, /, object_index: int, triangle: Triangle) -> None: ...
    @property
    def bounding_box(self, /) -> tuple[Vector3D, Vector3D]: ...
    def clear_texture(self, /) -> None: ...
    def clear_uvs(self, /) -> None: ...
    def copy(self, /) -> Mesh: ...
    def delete_duplicates(self, /, boundaries: Any |None = None) -> None: ...
    def export_dxf(self, /, path: Any |None = None, version: str = ...) -> str: ...
    def export_gltf(self, /, path: Any |None = None) -> str: ...
    def export_obj(self, /, path: Any |None = None, offset: float = 0.0) -> str: ...
    @staticmethod
    def from_indexed(vertices: Sequence[Vector3D], polygons: dict[str, Sequence[tuple[Any, Any]]], boundaries: Any |None = None, name: str = ..., node_attributes: Sequence[Any] |None = None) -> Mesh: ...
    @staticmethod
    def from_obj(path: Any, name: str |None = None) -> Mesh: ...
    def generate_uvs(self, /, projection: str = ...) -> None: ...
    def get_indexed(self, /) -> tuple[list[Vector3D], dict[str, list[tuple[Any, Any]]], dict[str, list[int]]]: ...
    def get_uv_coords(self, /) -> list[tuple[float, float]] |None: ...
    def has_texture(self, /) -> bool: ...
    def merge_duplicate_points(self, /, max_distance: float) -> list[int]: ...
    def mirror(self, /, axis: str = "x") -> Mesh: ...
    def mirror_geometry_only(self, /, axis: str = "x") -> Mesh:
        """
        Mirror the mesh geometry (and fix winding order) without touching UV coordinates.
        Unlike mirror(), this leaves uv_coords untouched so that remap_uvs_stacked can
        use the original stored (span_norm, chord_p) values even after geometry mirroring.
        """
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def objects(self, /) -> list[MeshObject]: ...
    def point_vectors(self, /) -> list[Vector3D]: ...
    @property
    def points(self, /) -> list[Vector3D]: ...
    def polygon_size(self, /) -> tuple[float, float, float]: ...
    @property
    def polygons(self, /) -> dict[str, list[tuple[Any, Any]]]: ...
    def remap_uvs_bilinear(self, /, back_left: tuple[float, float], back_right: tuple[float, float], front_right: tuple[float, float], front_left: tuple[float, float], bbox: tuple[float, float, float, float]) -> None: ...
    def remap_uvs_stacked(self, /, span_min: float, span_max: float, y_min: float, y_max: float, lower_offset: float, negate_span: bool) -> None:
        """
        Map per-vertex (span_normalized, chord_p) UV coords (stored by Panel::get_mesh
        when called with x_span_left/right) to final texture UV.
        
        span_normalized: rib x-value divided by max span, in [0,1] for the right half-wing.
        chord_p:         signed profile x-value (0 = LE, +ve = upper surface, -ve = lower).
        
        Stacking: upper panels (chord_p >= 0) sit above the LE line;
                  lower panels (chord_p < 0) are shifted by lower_offset so they form a
                  separate "lower sail" shape below.
        
        tex_u: derived from span (negate_span = true for the mirrored left half-wing).
        tex_v: 1 − normalised layout_y  (v-flip so WGPU v=0 is the top of the image).
        """
    def set_all_objects_textured(self, /, textured: bool = True) -> None: ...
    def set_texture_rgba(self, /, width: int, height: int, rgba: Sequence[int]) -> None: ...
    def set_uv_coords(self, /, uv_coords: Sequence[tuple[float, float]]) -> None: ...
    def triangularize(self, /) -> Mesh: ...
    @property
    def vertices(self, /) -> list[Vector3D]: ...

@final
class MeshObject:
    def __new__(cls, /, name: str, color: tuple[int, int, int] = ..., textured: bool = False, lines: Sequence[Line] |None = None, triangles: Sequence[Triangle] |None = None, quads: Sequence[Quad] |None = None) -> MeshObject: ...
    @property
    def color(self, /) -> tuple[int, int, int]: ...
    @color.setter
    def color(self, /, value: tuple[int, int, int]) -> None: ...
    @property
    def lines(self, /) -> list[Line]: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def quads(self, /) -> list[Quad]: ...
    @property
    def textured(self, /) -> bool: ...
    @textured.setter
    def textured(self, /, value: bool) -> None: ...
    @property
    def triangles(self, /) -> list[Triangle]: ...

@final
class Quad:
    def __new__(cls, /, a: int, b: int, c: int, d: int) -> Quad: ...
    @property
    def a(self, /) -> int: ...
    @a.setter
    def a(self, /, value: int) -> None: ...
    def as_tuple(self, /) -> tuple[int, int, int, int]: ...
    @property
    def b(self, /) -> int: ...
    @b.setter
    def b(self, /, value: int) -> None: ...
    @property
    def c(self, /) -> int: ...
    @c.setter
    def c(self, /, value: int) -> None: ...
    @property
    def d(self, /) -> int: ...
    @d.setter
    def d(self, /, value: int) -> None: ...

@final
class Triangle:
    def __new__(cls, /, a: int, b: int, c: int) -> Triangle: ...
    @property
    def a(self, /) -> int: ...
    @a.setter
    def a(self, /, value: int) -> None: ...
    def as_tuple(self, /) -> tuple[int, int, int]: ...
    @property
    def b(self, /) -> int: ...
    @b.setter
    def b(self, /, value: int) -> None: ...
    @property
    def c(self, /) -> int: ...
    @c.setter
    def c(self, /, value: int) -> None: ...

@final
class Triangulation2D:
    @property
    def nodes(self, /) -> list[Vector2D]: ...
    @property
    def triangles(self, /) -> list[tuple[int, int, int]]: ...

def duplicate_representatives(points: Sequence[Vector3D], max_distance: float) -> list[int]: ...
def find_duplicates(points: Sequence[Vector3D], max_distance: float) -> list[tuple[int, int]]: ...
def triangulate_with_holes(outline: PolyLine2D, holes: Sequence[PolyLine2D], min_area: float |None = None, max_area: float |None = None) -> Triangulation2D: ...
