from .vector import PolyLine2D, Vector2D, Vector3D
from collections.abc import Sequence
from typing import Any, final

@final
class Line:
    def __new__(cls, /, a: int, b: int) -> Line: ...
    @property
    def a(self, /) -> int: ...
    @a.setter
    def a(self, /, value: int) -> None: ...
    def as_tuple(self, /) -> tuple[int, int]: ...
    @property
    def b(self, /) -> int: ...
    @b.setter
    def b(self, /, value: int) -> None: ...

@final
class Mesh:
    def __add__(self, /, other: object) -> Mesh: ...
    def __copy__(self, /) -> Mesh: ...
    def __deepcopy__(self, /, _memo: Any) -> Mesh: ...
    def __getitem__(self, /, item: str) -> Mesh: ...
    def __json__(self, /) -> tuple[list[Vector3D], dict[str, list[tuple[Any, Any]]], dict[str, list[int]]]: ...
    def __new__(cls, /, name: str = ...) -> Mesh: ...
    def __repr__(self, /) -> str: ...
    def add_line(self, /, object_index: int, line: Line) -> None: ...
    def add_object(self, /, name: str, color: tuple[int, int, int] = ...) -> int: ...
    def add_point(self, /, point: Vector3D) -> int: ...
    def add_quad(self, /, object_index: int, quad: Quad) -> None: ...
    def add_triangle(self, /, object_index: int, triangle: Triangle) -> None: ...
    @property
    def bounding_box(self, /) -> tuple[Vector3D, Vector3D]: ...
    def copy(self, /) -> Mesh: ...
    def delete_duplicates(self, /, boundaries: Any |None = None) -> None: ...
    def export_dxf(self, /, path: Any |None = None, version: str = ...) -> str: ...
    def export_obj(self, /, path: Any |None = None, offset: float = 0.0) -> str: ...
    @staticmethod
    def from_indexed(vertices: Sequence[Vector3D], polygons: dict[str, Sequence[tuple[Any, Any]]], boundaries: Any |None = None, name: str = ..., node_attributes: Sequence[Any] |None = None) -> Mesh: ...
    @staticmethod
    def from_obj(path: Any, name: str |None = None) -> Mesh: ...
    def get_indexed(self, /) -> tuple[list[Vector3D], dict[str, list[tuple[Any, Any]]], dict[str, list[int]]]: ...
    def merge_duplicate_points(self, /, max_distance: float) -> list[int]: ...
    def mirror(self, /, axis: str = "x") -> Mesh: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def objects(self, /) -> list[MeshObject]: ...
    def point_vectors(self, /) -> list[Vector3D]: ...
    @property
    def points(self, /) -> list[Vector3D]: ...
    def polygon_size(self, /) -> tuple[float, float, float]: ...
    @property
    def polygons(self, /) -> dict[str, list[tuple[Any, Any]]]: ...
    def triangularize(self, /) -> Mesh: ...
    @property
    def vertices(self, /) -> list[Vector3D]: ...

@final
class MeshObject:
    def __new__(cls, /, name: str, color: tuple[int, int, int] = ..., lines: Sequence[Line] |None = None, triangles: Sequence[Triangle] |None = None, quads: Sequence[Quad] |None = None) -> MeshObject: ...
    @property
    def color(self, /) -> tuple[int, int, int]: ...
    @color.setter
    def color(self, /, value: tuple[int, int, int]) -> None: ...
    @property
    def lines(self, /) -> list[Line]: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def quads(self, /) -> list[Quad]: ...
    @property
    def triangles(self, /) -> list[Triangle]: ...

@final
class Quad:
    def __new__(cls, /, a: int, b: int, c: int, d: int) -> Quad: ...
    @property
    def a(self, /) -> int: ...
    @a.setter
    def a(self, /, value: int) -> None: ...
    def as_tuple(self, /) -> tuple[int, int, int, int]: ...
    @property
    def b(self, /) -> int: ...
    @b.setter
    def b(self, /, value: int) -> None: ...
    @property
    def c(self, /) -> int: ...
    @c.setter
    def c(self, /, value: int) -> None: ...
    @property
    def d(self, /) -> int: ...
    @d.setter
    def d(self, /, value: int) -> None: ...

@final
class Triangle:
    def __new__(cls, /, a: int, b: int, c: int) -> Triangle: ...
    @property
    def a(self, /) -> int: ...
    @a.setter
    def a(self, /, value: int) -> None: ...
    def as_tuple(self, /) -> tuple[int, int, int]: ...
    @property
    def b(self, /) -> int: ...
    @b.setter
    def b(self, /, value: int) -> None: ...
    @property
    def c(self, /) -> int: ...
    @c.setter
    def c(self, /, value: int) -> None: ...

@final
class Triangulation2D:
    @property
    def nodes(self, /) -> list[Vector2D]: ...
    @property
    def triangles(self, /) -> list[tuple[int, int, int]]: ...

def duplicate_representatives(points: Sequence[Vector3D], max_distance: float) -> list[int]: ...
def find_duplicates(points: Sequence[Vector3D], max_distance: float) -> list[tuple[int, int]]: ...
def triangulate_with_holes(outline: PolyLine2D, holes: Sequence[PolyLine2D], min_area: float |None = None, max_area: float |None = None) -> Triangulation2D: ...
