from .vector import PolyLine2D, PolyLine3D, Transformation, Vector2D, Vector3D
from typing import Any, final

@final
class Plane:
    def __new__(cls, /, p0: Vector3D, x_vector: Vector3D, y_vector: Vector3D) -> Plane: ...
    @staticmethod
    def from_transformation(transformation: Transformation) -> Plane: ...
    @property
    def normvector(self, /) -> Vector3D: ...
    @property
    def p0(self, /) -> Vector3D: ...
    def project(self, /, value: Vector3D |PolyLine3D) -> Any: ...
    def project_polyline(self, /, polyline: PolyLine3D) -> PolyLine2D: ...
    def project_vector(self, /, point: Vector3D) -> Vector2D: ...
    @property
    def transformation(self, /) -> Transformation: ...
    @property
    def x_vector(self, /) -> Vector3D: ...
    @property
    def y_vector(self, /) -> Vector3D: ...
