"""Auto-generated stubs for plane.

This module provides geometric calculations and types.
Stubs are generated from PyO3 introspection data.
"""

from typing import Any, Iterator, Optional, Union, overload

class Plane:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def project(self, *args: Any, **kwargs: Any) -> Any: ...
    def project_polyline(self, *args: Any, **kwargs: Any) -> Any: ...
    def project_vector(self, *args: Any, **kwargs: Any) -> Any: ...
