from .vector import PolyLine2D, PolyLine3D, Transformation, Vector2D, Vector3D
from collections.abc import Sequence
from typing import Any, final

@final
class Plane:
    def __new__(cls, /, arg0: Transformation |Vector3D |Sequence[float], arg1: Vector3D |Sequence[float] |None = None, arg2: Vector3D |Sequence[float] |None = None) -> Plane: ...
    @property
    def normvector(self, /) -> Vector3D: ...
    @property
    def p0(self, /) -> Vector3D: ...
    def project(self, /, value: Vector3D |Sequence[float] |PolyLine3D) -> Any: ...
    def project_polyline(self, /, polyline: PolyLine3D) -> PolyLine2D: ...
    def project_vector(self, /, point: Vector3D) -> Vector2D: ...
    @property
    def transformation(self, /) -> Transformation: ...
    @property
    def x_vector(self, /) -> Vector3D: ...
    @property
    def y_vector(self, /) -> Vector3D: ...
