from .vector import Interpolation, PolyLine2D, Vector2D
from collections.abc import Sequence
from typing import Any, final

@final
class BSplineCurve:
    def __copy__(self, /) -> BSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> BSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> BSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> BSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> BSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> BSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class BezierCurve:
    def __copy__(self, /) -> BezierCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> BezierCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> BezierCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> BezierCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> BezierCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> BezierCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class CubicBSplineCurve:
    def __copy__(self, /) -> CubicBSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> CubicBSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> CubicBSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> CubicBSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> CubicBSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> CubicBSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class LinSplineCurve:
    def __copy__(self, /) -> LinSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> LinSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> LinSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> LinSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> LinSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> LinSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class QuadBSplineCurve:
    def __copy__(self, /) -> QuadBSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> QuadBSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> QuadBSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> QuadBSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> QuadBSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> QuadBSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class SymmetricBSplineCurve:
    def __copy__(self, /) -> SymmetricBSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> SymmetricBSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> SymmetricBSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> SymmetricBSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> SymmetricBSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> SymmetricBSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class SymmetricBezierCurve:
    def __copy__(self, /) -> SymmetricBezierCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> SymmetricBezierCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> SymmetricBezierCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> SymmetricBezierCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> SymmetricBezierCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> SymmetricBezierCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class SymmetricCubicBSplineCurve:
    def __copy__(self, /) -> SymmetricCubicBSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> SymmetricCubicBSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> SymmetricCubicBSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> SymmetricCubicBSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> SymmetricCubicBSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> SymmetricCubicBSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...

@final
class SymmetricQuadBSplineCurve:
    def __copy__(self, /) -> SymmetricQuadBSplineCurve: ...
    def __deepcopy__(self, /, _memo: Any) -> SymmetricQuadBSplineCurve: ...
    def __new__(cls, /, controlpoints: Sequence[Vector2D |Sequence[float]]) -> SymmetricQuadBSplineCurve: ...
    @property
    def controlpoints(self, /) -> PolyLine2D: ...
    @controlpoints.setter
    def controlpoints(self, /, value: PolyLine2D |Sequence[Vector2D |Sequence[float]]) -> None: ...
    def copy(self, /) -> SymmetricQuadBSplineCurve: ...
    @staticmethod
    def fit(curve: PolyLine2D, numpoints: int) -> SymmetricQuadBSplineCurve: ...
    def get(self, /, value: float) -> Vector2D: ...
    def get_curvature(self, /, num: int) -> Interpolation: ...
    def get_derivate(self, /) -> SymmetricQuadBSplineCurve: ...
    def get_numpoints(self, /) -> int: ...
    def get_sequence(self, /, num: int) -> PolyLine2D: ...
    @property
    def numpoints(self, /) -> int: ...
    @numpoints.setter
    def numpoints(self, /, value: int) -> None: ...
    def set_numpoints(self, /, numpoints: int) -> None: ...
