"""Auto-generated stubs for spline.

This module provides geometric calculations and types.
Stubs are generated from PyO3 introspection data.
"""

from typing import Any, Iterator, Optional, Union, overload

class BSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class BezierCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class CubicBSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class LinSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class QuadBSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class SymmetricBSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class SymmetricBezierCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class SymmetricCubicBSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...

class SymmetricQuadBSplineCurve:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_curvature(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_derivate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_numpoints(self, *args: Any, **kwargs: Any) -> Any: ...
