"""Auto-generated stubs for vector.

This module provides geometric calculations and types.
Stubs are generated from PyO3 introspection data.
"""

from typing import Any, Iterator, Optional, Union, overload

class CutResult:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...

class Interpolation:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_length(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_positions(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_segment_lengthes(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_segments(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_tangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def mix(self, *args: Any, **kwargs: Any) -> Any: ...
    def move(self, *args: Any, **kwargs: Any) -> Any: ...
    def resample(self, *args: Any, **kwargs: Any) -> Any: ...
    def reverse(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale_nodes(self, *args: Any, **kwargs: Any) -> Any: ...
    def sub(self, *args: Any, **kwargs: Any) -> Any: ...
    def tolist(self, *args: Any, **kwargs: Any) -> Any: ...
    def walk(self, *args: Any, **kwargs: Any) -> Any: ...

class PolyLine2D:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def bool_union(self, *args: Any, **kwargs: Any) -> Any: ...
    def boundary(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self, *args: Any, **kwargs: Any) -> Any: ...
    def contains(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def cut(self, *args: Any, **kwargs: Any) -> Any: ...
    def fix_errors(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_area(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_length(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_positions(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_segment_lengthes(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_segments(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_tangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def mirror(self, *args: Any, **kwargs: Any) -> Any: ...
    def mix(self, *args: Any, **kwargs: Any) -> Any: ...
    def move(self, *args: Any, **kwargs: Any) -> Any: ...
    def normvectors(self, *args: Any, **kwargs: Any) -> Any: ...
    def offset(self, *args: Any, **kwargs: Any) -> Any: ...
    def resample(self, *args: Any, **kwargs: Any) -> Any: ...
    def reverse(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotate(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale_nodes(self, *args: Any, **kwargs: Any) -> Any: ...
    def segment_normals(self, *args: Any, **kwargs: Any) -> Any: ...
    def sub(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_3d(self, *args: Any, **kwargs: Any) -> Any: ...
    def tolist(self, *args: Any, **kwargs: Any) -> Any: ...
    def walk(self, *args: Any, **kwargs: Any) -> Any: ...

class PolyLine3D:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_length(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_positions(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_segment_lengthes(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_segments(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_tangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def mix(self, *args: Any, **kwargs: Any) -> Any: ...
    def move(self, *args: Any, **kwargs: Any) -> Any: ...
    def resample(self, *args: Any, **kwargs: Any) -> Any: ...
    def reverse(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale_nodes(self, *args: Any, **kwargs: Any) -> Any: ...
    def sub(self, *args: Any, **kwargs: Any) -> Any: ...
    def tolist(self, *args: Any, **kwargs: Any) -> Any: ...
    def walk(self, *args: Any, **kwargs: Any) -> Any: ...

class Rotation2D:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply(self, *args: Any, **kwargs: Any) -> Any: ...

class Transformation:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_polyline2(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_polyline3(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_vector2(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_vector3(self, *args: Any, **kwargs: Any) -> Any: ...
    def chain(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def reflection(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def translation(self, *args: Any, **kwargs: Any) -> Any: ...

class Vector2D:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def angle(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def cross(self, *args: Any, **kwargs: Any) -> Any: ...
    def distance(self, *args: Any, **kwargs: Any) -> Any: ...
    def dot(self, *args: Any, **kwargs: Any) -> Any: ...
    def length(self, *args: Any, **kwargs: Any) -> Any: ...
    def normalized(self, *args: Any, **kwargs: Any) -> Any: ...

class Vector3D:
    """Class stub."""
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def cross(self, *args: Any, **kwargs: Any) -> Any: ...
    def distance(self, *args: Any, **kwargs: Any) -> Any: ...
    def dot(self, *args: Any, **kwargs: Any) -> Any: ...
    def length(self, *args: Any, **kwargs: Any) -> Any: ...
    def normalized(self, *args: Any, **kwargs: Any) -> Any: ...

def cut(*args: Any, **kwargs: Any) -> Any: ...

def cut_2d(*args: Any, **kwargs: Any) -> Any: ...
