from collections.abc import Sequence
from typing import Any, final

@final
class CutResult:
    @property
    def ik_1(self, /) -> float: ...
    @property
    def ik_2(self, /) -> float: ...
    @property
    def point(self, /) -> Vector2D: ...
    @property
    def success(self, /) -> bool: ...

@final
class Interpolation:
    def __add__(self, /, other: object) -> Interpolation: ...
    def __copy__(self, /) -> Interpolation: ...
    def __deepcopy__(self, /, _memo: Any) -> Interpolation: ...
    def __iter__(self, /) -> Any: ...
    def __json__(self, /) -> list[list[float]]: ...
    def __len__(self, /) -> int: ...
    def __mul__(self, /, factor: object) -> Interpolation: ...
    def __new__(cls, /, nodes: Interpolation |PolyLine2D |Sequence[Vector2D |Sequence[float]], extrapolate: bool = True, validate: bool = True) -> Interpolation: ...
    def __sub__(self, /, other: object) -> Interpolation: ...
    def add(self, /, other: Interpolation) -> Interpolation: ...
    def copy(self, /) -> Interpolation: ...
    @property
    def curve(self, /) -> PolyLine2D: ...
    @property
    def extrapolate(self, /) -> bool: ...
    @extrapolate.setter
    def extrapolate(self, /, value: bool) -> None: ...
    def get(self, /, value: float, end: float |None = None) -> Any: ...
    def get_length(self, /) -> float: ...
    def get_positions(self, /, start: float, end: float) -> list[float]: ...
    def get_segment_lengthes(self, /) -> list[float]: ...
    def get_segments(self, /) -> list[Vector2D]: ...
    def get_tangents(self, /) -> list[Vector2D]: ...
    def get_value(self, /, value: float) -> float: ...
    def mix(self, /, other: Interpolation, factor: float) -> Interpolation: ...
    def move(self, /, offset: Vector2D |Sequence[float]) -> Interpolation: ...
    @property
    def nodes(self, /) -> list[Vector2D]: ...
    def resample(self, /, num_points: int) -> Interpolation: ...
    def reverse(self, /) -> Interpolation: ...
    def scale(self, /, factor: float |Vector2D |Sequence[float]) -> Interpolation: ...
    def scale_nodes(self, /, factors: Sequence[float]) -> Interpolation: ...
    def sub(self, /, other: Interpolation) -> Interpolation: ...
    def tolist(self, /) -> list[list[float]]: ...
    def walk(self, /, start: float, amount: float) -> float: ...

@final
class PolyLine2D:
    def __add__(self, /, other: object) -> PolyLine2D: ...
    def __copy__(self, /) -> PolyLine2D: ...
    def __deepcopy__(self, /, _memo: Any) -> PolyLine2D: ...
    def __getitem__(self, /, index: int) -> Vector2D: ...
    def __iter__(self, /) -> Any: ...
    def __json__(self, /) -> list[list[float]]: ...
    def __len__(self, /) -> int: ...
    def __mul__(self, /, factor: object) -> PolyLine2D: ...
    def __new__(cls, /, nodes: Sequence[Vector2D |Sequence[float]] |None = None) -> PolyLine2D: ...
    def __repr__(self, /) -> str: ...
    def __sub__(self, /, other: object) -> PolyLine2D: ...
    def add(self, /, other: PolyLine2D) -> PolyLine2D: ...
    def bool_intersection(self, /, other: PolyLine2D) -> list[PolyLine2D]: ...
    def bool_union(self, /, other: PolyLine2D) -> list[PolyLine2D]: ...
    def boundary(self, /) -> list[Vector2D]: ...
    def close(self, /) -> PolyLine2D: ...
    def contains(self, /, point: Vector2D |Sequence[float]) -> bool: ...
    def copy(self, /) -> PolyLine2D: ...
    def cut(self, /, other: Vector2D |Sequence[float] |PolyLine2D, second_point: Vector2D |Sequence[float] |None = None, nearest_ik: float |None = None) -> Any: ...
    def fix_errors(self, /) -> PolyLine2D: ...
    def get(self, /, value: float, end: float |None = None) -> Any: ...
    def get_area(self, /) -> float: ...
    def get_length(self, /) -> float: ...
    def get_positions(self, /, start: float, end: float) -> list[float]: ...
    def get_segment_lengthes(self, /) -> list[float]: ...
    def get_segments(self, /) -> list[Vector2D]: ...
    def get_tangents(self, /) -> list[Vector2D]: ...
    def mirror(self, /, p1: Vector2D |Sequence[float] |None = None, p2: Vector2D |Sequence[float] |None = None) -> PolyLine2D: ...
    def mix(self, /, other: PolyLine2D, factor: float) -> PolyLine2D: ...
    def move(self, /, offset: Vector2D |Sequence[float]) -> PolyLine2D: ...
    @property
    def nodes(self, /) -> list[Vector2D]: ...
    def normvectors(self, /) -> PolyLine2D: ...
    def offset(self, /, amount: float, simple: bool = False) -> PolyLine2D: ...
    def resample(self, /, num_points: int) -> PolyLine2D: ...
    def reverse(self, /) -> PolyLine2D: ...
    def rotate(self, /, angle: float, p1: Vector2D |Sequence[float] |None = None) -> PolyLine2D: ...
    def scale(self, /, factor: float |Vector2D |Sequence[float]) -> PolyLine2D: ...
    def scale_nodes(self, /, factors: Sequence[float]) -> PolyLine2D: ...
    def segment_normals(self, /) -> PolyLine2D: ...
    def sub(self, /, other: PolyLine2D) -> PolyLine2D: ...
    def to_3d(self, /) -> PolyLine3D: ...
    def tolist(self, /) -> list[list[float]]: ...
    def walk(self, /, start: float, amount: float) -> float: ...

@final
class PolyLine3D:
    def __add__(self, /, other: object) -> PolyLine3D: ...
    def __copy__(self, /) -> PolyLine3D: ...
    def __deepcopy__(self, /, _memo: Any) -> PolyLine3D: ...
    def __getitem__(self, /, index: int) -> Vector3D: ...
    def __iter__(self, /) -> Any: ...
    def __json__(self, /) -> list[list[float]]: ...
    def __len__(self, /) -> int: ...
    def __mul__(self, /, factor: object) -> PolyLine3D: ...
    def __new__(cls, /, nodes: Sequence[Vector3D |Sequence[float]] |None = None) -> PolyLine3D: ...
    def __repr__(self, /) -> str: ...
    def __sub__(self, /, other: object) -> PolyLine3D: ...
    def add(self, /, other: PolyLine3D) -> PolyLine3D: ...
    def copy(self, /) -> PolyLine3D: ...
    def get(self, /, value: float, end: float |None = None) -> Any: ...
    def get_length(self, /) -> float: ...
    def get_positions(self, /, start: float, end: float) -> list[float]: ...
    def get_segment_lengthes(self, /) -> list[float]: ...
    def get_segments(self, /) -> list[Vector3D]: ...
    def get_tangents(self, /) -> list[Vector3D]: ...
    def mix(self, /, other: PolyLine3D, factor: float) -> PolyLine3D: ...
    def move(self, /, offset: Vector3D |Sequence[float]) -> PolyLine3D: ...
    @property
    def nodes(self, /) -> list[Vector3D]: ...
    def resample(self, /, num_points: int) -> PolyLine3D: ...
    def reverse(self, /) -> PolyLine3D: ...
    def scale(self, /, factor: float |Vector3D |Sequence[float]) -> PolyLine3D: ...
    def scale_nodes(self, /, factors: Sequence[float]) -> PolyLine3D: ...
    def sub(self, /, other: PolyLine3D) -> PolyLine3D: ...
    def tolist(self, /) -> list[list[float]]: ...
    def walk(self, /, start: float, amount: float) -> float: ...

@final
class Rotation2D:
    def __new__(cls, /, angle: float) -> Rotation2D: ...
    def apply(self, /, vector: Vector2D |Sequence[float]) -> Vector2D: ...

@final
class Transformation:
    def __mul__(self, /, other: object) -> Transformation: ...
    def __new__(cls, /) -> Transformation: ...
    def apply(self, /, vector: Vector2D |Vector3D |Sequence[float]) -> Vector3D: ...
    def apply_polyline(self, /, polyline: PolyLine2D |PolyLine3D) -> PolyLine3D: ...
    def apply_vector3(self, /, vector: Vector3D) -> Vector3D: ...
    def chain(self, /, other: Transformation) -> Transformation: ...
    def copy(self, /) -> Transformation: ...
    @property
    def matrix(self, /) -> list[list[float]]: ...
    @staticmethod
    def reflection(normal: Vector3D |Sequence[float]) -> Transformation: ...
    @staticmethod
    def rotation(angle: float, axis: Vector3D |Sequence[float]) -> Transformation: ...
    @staticmethod
    def scale(scale: float) -> Transformation: ...
    @staticmethod
    def translation(vector: Vector2D |Vector3D |Sequence[float]) -> Transformation: ...

@final
class Vector2D:
    def __add__(self, /, other: object) -> Vector2D: ...
    def __copy__(self, /) -> Vector2D: ...
    def __deepcopy__(self, /, _memo: Any) -> Vector2D: ...
    def __eq__(self, /, other: object) -> bool: ...
    def __ge__(self, /, other: object) -> bool: ...
    def __getitem__(self, /, index: int) -> float: ...
    def __gt__(self, /, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __iter__(self, /) -> Any: ...
    def __json__(self, /) -> list[float]: ...
    def __le__(self, /, other: object) -> bool: ...
    def __len__(self, /) -> int: ...
    def __lt__(self, /, other: object) -> bool: ...
    def __mul__(self, /, other: object) -> Vector2D: ...
    def __new__(cls, /, values: Sequence[float] |None = None) -> Vector2D: ...
    def __repr__(self, /) -> str: ...
    def __setitem__(self, /, index: int, value: float) -> None: ...
    def __str__(self, /) -> str: ...
    def __sub__(self, /, other: object) -> Vector2D: ...
    def __truediv__(self, /, factor: object) -> Vector2D: ...
    def angle(self, /) -> float: ...
    def copy(self, /) -> Vector2D: ...
    def cross(self, /, other: Vector2D) -> float: ...
    def distance(self, /, other: Vector2D) -> float: ...
    def dot(self, /, other: Vector2D) -> float: ...
    def length(self, /) -> float: ...
    def normalized(self, /) -> Vector2D: ...
    @property
    def x(self, /) -> float: ...
    @x.setter
    def x(self, /, value: float) -> None: ...
    @property
    def y(self, /) -> float: ...
    @y.setter
    def y(self, /, value: float) -> None: ...

@final
class Vector3D:
    def __add__(self, /, other: object) -> Vector3D: ...
    def __copy__(self, /) -> Vector3D: ...
    def __deepcopy__(self, /, _memo: Any) -> Vector3D: ...
    def __eq__(self, /, other: object) -> bool: ...
    def __ge__(self, /, other: object) -> bool: ...
    def __getitem__(self, /, index: int) -> float: ...
    def __gt__(self, /, other: object) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __iter__(self, /) -> Any: ...
    def __json__(self, /) -> list[float]: ...
    def __le__(self, /, other: object) -> bool: ...
    def __len__(self, /) -> int: ...
    def __lt__(self, /, other: object) -> bool: ...
    def __mul__(self, /, other: object) -> Vector3D: ...
    def __new__(cls, /, values: Sequence[float] |None = None) -> Vector3D: ...
    def __repr__(self, /) -> str: ...
    def __setitem__(self, /, index: int, value: float) -> None: ...
    def __str__(self, /) -> str: ...
    def __sub__(self, /, other: object) -> Vector3D: ...
    def __truediv__(self, /, factor: object) -> Vector3D: ...
    def copy(self, /) -> Vector3D: ...
    def cross(self, /, other: Vector3D) -> Vector3D: ...
    def distance(self, /, other: Vector3D) -> float: ...
    def dot(self, /, other: Vector3D) -> float: ...
    def length(self, /) -> float: ...
    def normalized(self, /) -> Vector3D: ...
    @property
    def x(self, /) -> float: ...
    @x.setter
    def x(self, /, value: float) -> None: ...
    @property
    def y(self, /) -> float: ...
    @y.setter
    def y(self, /, value: float) -> None: ...
    @property
    def z(self, /) -> float: ...
    @z.setter
    def z(self, /, value: float) -> None: ...

def cut(l1_p1: Vector2D |Sequence[float], l1_p2: Vector2D |Sequence[float], l2_p1: Vector2D |Sequence[float], l2_p2: Vector2D |Sequence[float]) -> CutResult: ...
def cut_2d(l1_p1: Vector2D |Sequence[float], l1_p2: Vector2D |Sequence[float], l2_p1: Vector2D |Sequence[float], l2_p2: Vector2D |Sequence[float]) -> CutResult: ...
