from .mesh import Mesh
from typing import final

@final
class MeshActor:
    """
    Pre-computed mesh actor: holds CPU-side vertex data for all edge variants.
    Create once from a Mesh; add/remove from the renderer cheaply via visibility toggle.
    """
    def __new__(cls, /, mesh: Mesh, draw_edges: bool = False, boundary_only: bool = False) -> MeshActor: ...

@final
class NativeWgpuRenderer:
    def __new__(cls, /, platform: str, window_id: int, width: int, height: int, display_id: int |None = None) -> NativeWgpuRenderer: ...
    def add_actor(self, /, actor: MeshActor) -> None: ...
    def add_mesh(self, /, name: str, mesh: Mesh, draw_edges: bool |None = None, boundary_only: bool |None = None) -> None: ...
    def clear_meshes(self, /) -> None: ...
    def close(self, /) -> None: ...
    def remove_actor(self, /, actor: MeshActor) -> None: ...
    def remove_mesh(self, /, name: str) -> None: ...
    def render(self, /) -> None: ...
    def resize(self, /, width: int, height: int) -> None: ...
    def set_actor_edges(self, /, name: str, draw_edges: bool, boundary_only: bool) -> None: ...
    def set_actor_visibility(self, /, name: str, visible: bool) -> None: ...
    def set_boundary_only(self, /, enabled: bool) -> None: ...
    def set_camera(self, /, yaw: float, pitch: float, distance: float, target_x: float, target_y: float, target_z: float) -> None: ...
    def set_color_bounds(self, /, min_val: float, max_val: float) -> None: ...
    def set_draw_edges(self, /, enabled: bool) -> None: ...
    def set_mesh(self, /, mesh: Mesh) -> None: ...
    def set_projection(self, /, mode: str) -> None: ...
