from .mesh import Mesh
from typing import final

@final
class NativeWgpuRenderer:
    def __new__(cls, /, platform: str, window_id: int, width: int, height: int, display_id: int |None = None) -> NativeWgpuRenderer: ...
    def close(self, /) -> None: ...
    def render(self, /) -> None: ...
    def resize(self, /, width: int, height: int) -> None: ...
    def set_camera(self, /, yaw: float, pitch: float, distance: float, target_x: float, target_y: float, target_z: float) -> None: ...
    def set_mesh(self, /, mesh: Mesh) -> None: ...
    def set_projection(self, /, mode: str) -> None: ...
